services:
  cryze-android-service:
    image: cryze-android-emulator
    network_mode: host
    build: 
      context: android
    container_name: cryze-android-emulator
    privileged: true
    command:
      - bash
      - -c
      - |
         ./install_apk.sh
    tty: true
    stdin_open: true

  cryze-server-service:
    image: cryze-server
    network_mode: host
    build:
      context: server
    container_name: cryze-server

  emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: cryze-emulator
    ports:
      - "6080:6080"
      - "3030:3030"
    volumes:
      - D:\Documents\cryze\cryze:/home/androidusr/cryze:rw
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm:/dev/kvm
    restart: unless-stopped
    privileged: true
  
