version: "4"

networks:
  android_server_network:
    driver: bridge

services:
# Launch emulator and appium instance
  android-service:
    image: android-emulator
    build: 
      context: android
    ports:
      - 4725:4725
      - 3030:3030
    container_name: android
    environment:
      - APPIUM_PORT=4725
    privileged: true
    command:
      - bash
      - -c
      - |
         ./install_apk.sh
    tty: true
    stdin_open: true
    networks:
      - android_server_network

  # cryze-server-service:
  #   image: cryze-server
  #   build:
  #     context: server
  #   ports:
  #     - 8080:8080
  #   container_name: cryze-server
  #   networks:
  #     - android_server_network
  
