version: "4"
services:
# Launch emulator and appium instance
  cryze-android-service:
    image: cryze-android-emulator
    network_mode: host
    build: 
      context: android
    container_name: cryze-android0-emulator
    privileged: true
    command:
      - bash
      - -c
      - |
         ./install_apk.sh
    tty: true
    stdin_open: true

  cryze-server-service:
    image: cryze-server
    network_mode: host
    build:
      context: server
    container_name: cryze-server
  
